alter table public.station_settings
  add column if not exists site_title text default 'Staley Street Weather',
  add column if not exists station_label text default 'KVAMARI042',
  add column if not exists station_location text default 'Marion, Virginia',
  add column if not exists timezone text default 'America/New_York',
  add column if not exists sms_enabled boolean default false,
  add column if not exists alarm_thresholds jsonb default '{
    "windMph": 30,
    "tempPercent": 10,
    "humidityPercent": 15,
    "changeWindowMinutes": 60,
    "snowInches": 1,
    "precipRateInches": 1,
    "freezeTempF": 32
  }'::jsonb,
  add column if not exists last_daily_report_date text;

create table if not exists public.weather_observations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  station_id text,
  temp numeric,
  humidity numeric,
  pressure numeric,
  wind_speed numeric,
  wind_gust numeric,
  precip_rate numeric,
  precip_total numeric,
  obs_time_utc timestamptz
);
